---
title: "Mediation analysis"
author: "Russ Poldrack"
date: "November 2, 2014"
output: html_document
---

This is code to run the mediation analysis for fatigue as mediator of relation between day of week and brain connectivity

```{r}
library(mediation)
source('http://s3.amazonaws.com/openfmri/ds031/timeseries_analyses/data_utilities.R')
source('http://s3.amazonaws.com/openfmri/ds031/timeseries_analyses/load_myconnectome_data.R')

behav=load_behav_data()
wincorr=load_fmri_data()
```

### Does fatigue mediate the relation between tu_th and Dorsal Attention?

```{r}
fatigue=behav$panas.fatigue
tu_th=behav$tu_th

da1=array(NA,dim=length(wincorr[,5]))
da1[behav$date %in% wincorr$date]=wincorr[,5]
da2=array(NA,dim=length(wincorr[,5]))
da2[behav$date %in% wincorr$date]=wincorr[,6]

med_data=as.data.frame(cbind(fatigue,da1,da2,tu_th))
med_data=med_data[!is.na(apply(med_data,1,sum)),]
```

#### First test for DA1

```{r}
med.fit=lm(fatigue ~ tu_th,data=med_data)
out.fit=lm(da1 ~ fatigue + tu_th,data=med_data)
m=mediate(med.fit,out.fit,treat='tu_th',mediator='fatigue',robustSE = TRUE, sims = 1000)

summary(m)
```

#### Now test for DA2
```{r}
out.fit=lm(da2 ~ fatigue + tu_th,data=med_data)
m=mediate(med.fit,out.fit,treat='tu_th',mediator='fatigue',robustSE = TRUE, sims = 1000)

summary(m)
```

