---
title: "Snyderome data preparation"
author: "Russ Poldrack"
date: "May 18, 2015"
output: html_document
---

# Commparison of MyConnectome to Snyderome RNA-seq data

The Snyderome RNA-seq data were obtained from [GEO](http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE33029).  

## First prepare Snyderome data

```{r setup, echo=FALSE,message=FALSE}
basedir=Sys.getenv('MYCONNECTOME_DIR')
if (basedir==''){basedir='/Users/poldrack/data_unsynced/myconnectome'}

library(DESeq)

filenames=read.table('http://s3.amazonaws.com/openfmri/ds031/RNA-seq/snyderome/htcount_files.txt')
filenames=as.character(filenames$V1)
htcount_files=c()
for (i in 1:length(filenames)){
  htcount_files=rbind(htcount_files,c(filenames[i],filenames[i],i))
}
cdsFull=newCountDataSetFromHTSeqCount(htcount_files,
          directory="http://s3.amazonaws.com/openfmri/ds031/RNA-seq/snyderome")
cdsFull = estimateSizeFactors( cdsFull )

```

```{r cleanup, echo=FALSE,message=FALSE}
# get mean expression for each gene across sesssions
rs = rowMeans ( counts ( cdsFull ))
allgenes=rownames(counts(cdsFull))

# remove genes with 
use = (rs>4 & rs<10000)
cds=cdsFull[use,]
usedgenes=rownames(counts(cds))

```


```{r varstab, echo=FALSE,message=FALSE}
# generate variance-stabilized count data and save to file

cdsBlind = estimateDispersions( cds, method="blind" ,fitType='local')
vsd = varianceStabilizingTransformation( cdsBlind )
vsdata=getVarianceStabilizedData(cdsBlind)
dir.create(file.path(sprintf('%s/rna-seq',basedir), 'snyderome'), showWarnings = FALSE)
write.table(vsdata,sprintf('%s/rna-seq/snyderome/varstab_data.txt',basedir))

```

## Diagnostic figures

### Dispersion estimates
```{r plotDispEsts, echo=FALSE,message=FALSE, fig.width=16, fig.height=12}
# plot some diagnostic figures

plotDispEsts( cdsBlind )


```

### SD vs. count before and after correction
```{r plotSD, echo=FALSE,message=FALSE, fig.width=16, fig.height=12}
#plot SD vs. count before and after correction
library(vsn)
par(mfrow=c(1,2))
notAllZero = (rowSums(counts(cds))>0)
meanSdPlot(log2(counts(cds)[notAllZero, ] + 1), ylim = c(0,2.5))
meanSdPlot(vsd[notAllZero, ], ylim = c(0,2.5))

```

### Clusters of genes/sessions

```{r plotGeneClust,results='asis', echo=FALSE,message=FALSE,warning=FALSE,error=FALSE, fig.width=16, fig.height=12}
# plot clusters of genes/subjects
library("RColorBrewer")
library("gplots")
select = order(rowMeans(counts(cdsBlind)), decreasing=TRUE)[1:30]
hmcol = colorRampPalette(brewer.pal(9, "GnBu"))(100)
heatmap.2(exprs(vsd)[select,], col = hmcol, trace="none", margin=c(10, 6))

```

### Plot clusters of sessions - to look for outliers

```{r plotSubClust,results='asis', echo=FALSE,message=FALSE,warning=FALSE,error=FALSE, fig.width=16, fig.height=12}
# plot clusters of subjects - to look for outliers
dists = dist( t( exprs(vsd) ) )
mat = as.matrix( dists )
heatmap.2(mat, trace="none", col = rev(hmcol), margin=c(13, 13))


```

## Compare expression to MyConnectome

```{r compare, echo=FALSE,message=FALSE,warning=FALSE,error=FALSE, fig.width=16, fig.height=16}

mycdata=read.table(sprintf('%s/rna-seq/varstab_data_prefiltered.txt',basedir))
mycmean=apply(mycdata,1,mean)
snymean=apply(vsdata,1,mean)

cat(sprintf('Snyderome: %d genes\n',length(snymean)))
cat(sprintf('MyConnectome: %d genes\n',length(mycmean)))
mycgenes=names(mycmean)
snygenes=names(snymean)
mycmatch=mycgenes %in% snygenes
snymatch=snygenes %in% mycgenes

mycmean_match=mycmean[mycmatch]
snymean_match=snymean[snymatch]
cat(sprintf('Overlap: %d genes\n',length(snymean_match)))
if (sum(names(mycmean_match)==names(snymean_match)) != length(snymean_match)) {
  cat('there is a problem with gene name mismatch')
}

cat(sprintf('Correlation between datasets = %f\n',cor(mycmean_match,snymean_match)))


plot(mycmean_match,snymean_match,main='MyConnectome vs. Snyderome',xlab='MyConnectome expression',ylab='Snyderome expression')
```
