---
title: "Timseries Power Simulation"
author: "Russ Poldrack"
date: "December 16, 2014"
output: html_document
---

Simulate the generation of timeseries for one of the observed relations in the MyConnectome study, and assess statistical power.

First load up the data.

```{r}
library(forecast)
source('http://s3.amazonaws.com/openfmri/ds031/timeseries_analyses/load_myconnectome_data.R')
source('http://s3.amazonaws.com/openfmri/ds031/timeseries_analyses/data_utilities.R')
source('http://s3.amazonaws.com/openfmri/ds031/timeseries_analyses/est_bivariate_arima_model.R')
behav=load_behav_data()
wincorr=load_fmri_data('wincorr')
```

Get the timeseries representations for Default Mode connectivity (y) and positive mood (x).
```{r}
alldays=get_alldays(behav,wincorr)
behav_keep=subset(behav,select=c(date,panas.fatigue))
y=get_x_ts(behav_keep,alldays)
x=get_y_ts(wincorr,alldays,10)
```


Compute the power for a Pearson correlation
```{r}
cor.pear=cor(x,y,use='complete.obs')
library(pwr)
n.days.80per.power.pearson = ceiling(pwr.r.test(r = cor.pear, sig.level = 0.05, power = 0.8, alternative = "greater")$n)

```

